.SH OPTIONS

The following command-line options are recognized by
.BR ocamlbuild (1).

.TP
\fB\-version\fR
Display the version
.TP
\fB\-\-version\fR
same as \-version
.TP
\fB\-vnum\fR
Display the version number
.TP
\fB\-\-vnum\fR
same as \-vnum
.TP
\fB\-quiet\fR
Make as quiet as possible
.TP
\fB\-verbose\fR <level>
Set the verbosity level on a scale from 0 to 8 (included)
.TP
\fB\-documentation\fR
Show rules and flags
.TP
\fB\-log\fR <file>
Set log file
.TP
\fB\-no\-log\fR
No log file
.TP
\fB\-clean\fR
Remove build directory and other files, then exit
.TP
\fB\-r\fR
Traverse directories by default (true: traverse)
.TP
\fB\-I\fR <path>
Add to include directories
.TP
\fB\-Is\fR <path,...>
(same as above, but accepts a (comma or blank)\-separated list)
.TP
\fB\-X\fR <path>
Directory to ignore
.TP
\fB\-Xs\fR <path,...>
(idem)
.TP
\fB\-lib\fR <flag>
Link to this ocaml library
.TP
\fB\-libs\fR <flag,...>
(idem)
.TP
\fB\-mod\fR <module>
Link to this ocaml module
.TP
\fB\-mods\fR <module,...>
(idem)
.TP
\fB\-pkg\fR <package>
Link to this ocaml findlib package
.TP
\fB\-pkgs\fR <package,...>
(idem)
.TP
\fB\-package\fR <package>
(idem)
.TP
\fB\-syntax\fR <syntax>
Specify syntax using ocamlfind
.TP
\fB\-lflag\fR <flag>
Add to ocamlc link flags
.TP
\fB\-lflags\fR <flag,...>
(idem)
.TP
\fB\-cflag\fR <flag>
Add to ocamlc compile flags
.TP
\fB\-cflags\fR <flag,...>
(idem)
.TP
\fB\-docflag\fR <flag>
Add to ocamldoc flags
.TP
\fB\-docflags\fR <flag,...>
(idem)
.TP
\fB\-yaccflag\fR <flag>
Add to ocamlyacc flags
.TP
\fB\-yaccflags\fR <flag,...>
(idem)
.TP
\fB\-lexflag\fR <flag>
Add to ocamllex flags
.TP
\fB\-lexflags\fR <flag,...>
(idem)
.TP
\fB\-ppflag\fR <flag>
Add to ocaml preprocessing flags
.TP
\fB\-pp\fR <flag,...>
(idem)
.TP
\fB\-tag\fR <tag>
Add to default tags
.TP
\fB\-tags\fR <tag,...>
(idem)
.TP
\fB\-plugin\-tag\fR <tag>
Use this tag when compiling the myocamlbuild.ml plugin
.TP
\fB\-plugin\-tags\fR <tag,...>
(idem)
.TP
\fB\-tag\-line\fR <tag>
Use this line of tags (as in _tags)
.TP
\fB\-show\-tags\fR <path>
Show tags that applies on that pathname
.TP
\fB\-ignore\fR <module,...>
Don't try to build these modules
.TP
\fB\-no\-links\fR
Don't make links of produced final targets
.TP
\fB\-no\-skip\fR
Don't skip modules that are requested by ocamldep but cannot be built
.TP
\fB\-no\-hygiene\fR
Don't apply sanity\-check rules
.TP
\fB\-no\-plugin\fR
Don't build myocamlbuild.ml
.TP
\fB\-no\-stdlib\fR
Don't ignore stdlib modules
.TP
\fB\-dont\-catch\-errors\fR
Don't catch and display exceptions (useful to display the call stack)
.TP
\fB\-just\-plugin\fR
Just build myocamlbuild.ml
.TP
\fB\-byte\-plugin\fR
Don't use a native plugin but bytecode
.TP
\fB\-plugin\-option\fR
Use the option only when plugin is run
.TP
\fB\-sanitization\-script\fR
Change the file name for the generated sanitization script
.TP
\fB\-no\-sanitize\fR
Do not generate sanitization script
.TP
\fB\-nothing\-should\-be\-rebuilt\fR
Fail if something needs to be rebuilt
.TP
\fB\-classic\-display\fR
Display executed commands the old\-fashioned way
.TP
\fB\-use\-menhir\fR
Use menhir instead of ocamlyacc
.TP
\fB\-use\-jocaml\fR
Use jocaml compilers instead of ocaml ones
.TP
\fB\-use\-ocamlfind\fR
Use the 'ocamlfind' wrapper instead of using Findlib directly to determine command\-line arguments. Use \-no\-ocamlfind to disable. Implies \-plugin\-use\-ocamlfind.
.TP
\fB\-no\-ocamlfind\fR
Don't use ocamlfind. Implies \-plugin\-no\-ocamlfind.
.TP
\fB\-plugin\-use\-ocamlfind\fR
Use the 'ocamlfind' wrapper for building myocamlbuild.ml
.TP
\fB\-plugin\-no\-ocamlfind\fR
Don't use ocamlfind for building myocamlbuild.ml
.TP
\fB\-toolchain\fR <toolchain>
Set the Findlib toolchain to use. The default toolchain is always used for building myocamlbuild.ml.
.TP
\fB\-j\fR <N>
Allow N jobs at once (0 for unlimited)
.TP
\fB\-build\-dir\fR <path>
Set build directory (implies no\-links)
.TP
\fB\-install\-lib\-dir\fR <path>
Set the install library directory
.TP
\fB\-install\-bin\-dir\fR <path>
Set the install binary directory
.TP
\fB\-where\fR
Display the install library directory
.TP
\fB\-which\fR <command>
Display path to the tool command
.TP
\fB\-ocamlc\fR <command>
Set the OCaml bytecode compiler
.TP
\fB\-plugin\-ocamlc\fR <command>
Set the OCaml bytecode compiler used when building myocamlbuild.ml (only)
.TP
\fB\-ocamlopt\fR <command>
Set the OCaml native compiler
.TP
\fB\-plugin\-ocamlopt\fR <command>
Set the OCaml native compiler used when building myocamlbuild.ml (only)
.TP
\fB\-ocamldep\fR <command>
Set the OCaml dependency tool
.TP
\fB\-ocamldoc\fR <command>
Set the OCaml documentation generator
.TP
\fB\-ocamlyacc\fR <command>
Set the ocamlyacc tool
.TP
\fB\-menhir\fR <command>
Set the menhir tool (use it after \-use\-menhir)
.TP
\fB\-ocamllex\fR <command>
Set the ocamllex tool
.TP
\fB\-ocamlmklib\fR <command>
Set the ocamlmklib tool
.TP
\fB\-ocamlmktop\fR <command>
Set the ocamlmktop tool
.TP
\fB\-ocamlrun\fR <command>
Set the ocamlrun tool
.TP
\fB\-\-\fR
Stop argument processing, remaining arguments are given to the user program
.TP
\fB\-help\fR
Display this list of options
.TP
\fB\-\-help\fR
Display this list of options

.PP
